ADD component for login pages
Sewakantor/frontend pull request #20
Opened 2021-12-29 14:44 UTC by adiwahyudi

adding component for login pages, here is the preview :

![image](https://user-images.githubusercontent.com/24860132/147673781-11ebc9b0-d424-4d9c-b97d-883872d9b4d3.png)

![image](https://user-images.githubusercontent.com/24860132/147673706-eb5f1d0e-4303-4735-8c05-c95561c6df69.png)

2021-12-29 16:45 UTC, avtara requested changes
Conflict at index.js

2021-12-29 19:12 UTC, adiwahyudi commented
> Conflict at index.js

next time, make index js clear first ya

2021-12-30 08:45 UTC, rchmatagung approved these changes

2021-12-30 08:48 UTC, rchmatagung approved these changes

2021-12-30 08:51 UTC, avtara approved these changes

2021-12-30 08:51 UTC, merged